---
version: '3'

services:
  jenkins:
    build: jenkins/.
    hostname: jenkins
    container_name: jenkins
    volumes:
      - /var/jenkins_home
      - ./jenkins/gitconfig:/var/jenkins_home/.gitconfig
      - ./jenkins/init.groovy.d:/var/jenkins_home/init.groovy.d
      - ./jenkins/dsl_seed_job.groovy:/var/jenkins_home/workspace/dsl-seed-job/dsl_seed_job.groovy
      - /var/run/docker.sock:/var/run/docker.sock


  tom-a:
    build: tomcat/.
    hostname: tom-a
    container_name: tom-a
    volumes:
      - ./tomcat/a/server.xml:/usr/local/tomcat/conf/server.xml
      - ./tomcat/users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./tomcat/web.xml:/usr/local/tomcat/webapps/ROOT/WEB-INF/web.xml
      - ./tomcat/manager-context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml

  tom-b:
    build:
      context: tomcat/.
      dockerfile: ./Dockerfile-log4j2
    hostname: tom-b
    container_name: tom-b
    volumes:
      - ./tomcat/b/server.xml:/usr/local/tomcat/conf/server.xml
      - ./tomcat/b/log4j.properties:/usr/local/tomcat/lib/log4j.properties
      - ./tomcat/users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./tomcat/web.xml:/usr/local/tomcat/webapps/ROOT/WEB-INF/web.xml
      - ./tomcat/manager-context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml

  tom-c:
    build: tomcat/.
    hostname: tom-c
    container_name: tom-c
    volumes:
      - ./tomcat/c/server.xml:/usr/local/tomcat/conf/server.xml
      - ./tomcat/users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./tomcat/web.xml:/usr/local/tomcat/webapps/ROOT/WEB-INF/web.xml
      - ./tomcat/manager-context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml

  httpd:
    build: httpd/.
    hostname: httpd
    container_name: httpd
    ports:
      - 80:80
      - 8080:8080
      - 9000:9000
    volumes:
      - ./httpd/jk.conf:/etc/apache2/mods-available/jk.conf
      - ./httpd/workers.properties:/etc/libapache2-mod-jk/workers.properties
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./httpd/vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf

  postgres:
    build: postgres/.
    image: postgres:10.5
    hostname: postgres
    container_name: postgres
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql


  sonarqube:
    build: sonarqube/.
    hostname: sonarqube
    container_name: sonarqube
